workflows:
  android-build:
    name: RevOx Android Release Build

    environment:
      android_signing:
        - revox

    scripts:
      - name: Build APK
        script: |
          cd mobile/android
          chmod +x gradlew
          ./gradlew assembleRelease

    artifacts:
      - mobile/android/app/build/outputs/apk/release/*.apk
