workflows:

  android-build:

    name: RevOx Android Build


    environment:

      java: 21

      android_signing:
        - revox



    scripts:


      - name: Install dependencies

        script: |

          cd mobile

          npm install

          npm install @capacitor/android @capacitor/core @capacitor/cli

          npm install @capacitor/assets --save-dev



      - name: Generate app icon

        script: |

          cd mobile

          npx capacitor-assets generate



      - name: Auto update version

        script: |

          cd mobile/android

          python3 <<'PY'

          import re
          import os


          file = "app/build.gradle"


          with open(file, "r") as f:
              data = f.read()


          build = os.environ.get(
              "BUILD_NUMBER",
              "1"
          )


          data = re.sub(
              r'versionCode\s+\d+',
              f'versionCode {build}',
              data
          )


          data = re.sub(
              r'versionName\s+"[^"]+"',
              f'versionName "1.{build}"',
              data
          )


          with open(file, "w") as f:
              f.write(data)


          print("Version:", "1."+build)
          print("Code:", build)

          PY



      - name: Sync Capacitor

        script: |

          cd mobile

          npx cap sync android



      - name: Build APK

        script: |

          cd mobile/android

          chmod +x gradlew

          ./gradlew assembleRelease



      - name: Sign APK

        script: |

          APK=$(find mobile/android/app/build/outputs/apk -name "*.apk" | head -1)


          echo "Signing:"
          echo "$APK"


          $ANDROID_HOME/build-tools/36.0.0/apksigner sign \
          --ks $CM_KEYSTORE_PATH \
          --ks-key-alias $CM_KEY_ALIAS \
          --ks-pass pass:$CM_KEYSTORE_PASSWORD \
          --key-pass pass:$CM_KEY_PASSWORD \
          "$APK"



          echo "Verify signature"


          $ANDROID_HOME/build-tools/36.0.0/apksigner verify \
          --verbose "$APK"



      - name: Prepare APK

        script: |

          mkdir -p output


          APK=$(find mobile/android/app/build/outputs/apk -name "*.apk" | head -1)


          cp "$APK" output/RevOx.apk




    artifacts:

      - output/RevOx.apk
