workflows:
  android-build:
    name: RevOx Android Release Build

    environment:
      android_signing:
        - revox

    scripts:

      - name: Install dependencies
        script: |
          npm install

      - name: Install Capacitor CLI
        script: |
          npm install --save-dev @capacitor/cli

      - name: Sync Capacitor
        script: |
          npx cap sync android

      - name: Build APK
        script: |
          cd mobile/android
          chmod +x gradlew
          ./gradlew assembleRelease

      - name: Rename APK
        script: |
          mv mobile/android/app/build/outputs/apk/release/app-release.apk mobile/android/app/build/outputs/apk/release/RevOx.apk

    artifacts:
      - mobile/android/app/build/outputs/apk/release/RevOx.apk
